window.NaijaPawsData = {
  admin: {
    whatsapp: "2348012345678",
    email: "hello@naijapaws.com",
  },
  demoUsers: [
    {
      id: 1,
      fullName: "Adaeze Okonkwo",
      email: "buyer@naijapaws.demo",
      phone: "08012345678",
      password: "Password1",
      role: "buyer",
    },
    {
      id: 2,
      fullName: "Adeniyi Kennels",
      email: "seller@naijapaws.demo",
      phone: "08098765432",
      password: "Password1",
      role: "seller",
      approved: true,
    },
    {
      id: 3,
      fullName: "NaijaPaws Admin",
      email: "admin@naijapaws.demo",
      phone: "08011112222",
      password: "Password1",
      role: "admin",
      approved: true,
    },
  ],
  stats: {
    dogsListed: 248,
    verifiedSellers: 78,
    completedOrders: 1163,
    products: 142,
  },
  states: [
    "Abuja",
    "Abia",
    "Anambra",
    "Delta",
    "Edo",
    "Enugu",
    "Kaduna",
    "Kano",
    "Lagos",
    "Ogun",
    "Oyo",
    "Rivers",
  ],
  testimonials: [
    {
      name: "Miriam A.",
      location: "Lagos",
      quote: "The browsing experience feels clean and trustworthy. I found a vaccinated puppy in two days.",
    },
    {
      name: "Kelvin O.",
      location: "Port Harcourt",
      quote: "I listed my stud dog, got serious enquiries fast, and the checkout flow was much easier to explain.",
    },
    {
      name: "Tolu S.",
      location: "Abuja",
      quote: "The vet request flow is straightforward and the safety reminders are visible without being annoying.",
    },
  ],
  dogs: [
    {
      id: 101,
      title: "Champion Bloodline German Shepherd",
      category: "sale",
      breed: "German Shepherd",
      gender: "male",
      state: "Lagos",
      city: "Lekki",
      price: 850000,
      ageMonths: 14,
      temperament: "friendly",
      isPedigree: true,
      isVaccinated: true,
      isFeatured: true,
      seller: "Adeniyi Kennels",
      sellerInitials: "AK",
      description: "A social and obedient working-line German Shepherd with strong structure, complete vaccinations, and clean lineage documentation. Ideal for family security and companion homes.",
      purpose: ["security", "family"],
      healthStatus: "Excellent",
      vaccinationDetails: "Rabies, DHPP, deworming current",
      rating: 4.8,
      reviewCount: 17,
      images: [
        "https://images.unsplash.com/photo-1517849845537-4d257902454a?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=1200&q=80",
      ],
    },
    {
      id: 102,
      title: "Playful Labrador Retriever Puppy",
      category: "sale",
      breed: "Labrador Retriever",
      gender: "female",
      state: "Abuja",
      city: "Gwarinpa",
      price: 420000,
      ageMonths: 6,
      temperament: "friendly",
      isPedigree: false,
      isVaccinated: true,
      isFeatured: true,
      seller: "Golden Trails Pets",
      sellerInitials: "GT",
      description: "Well-socialized Labrador puppy raised around children, crate trained, and already responding to basic commands.",
      purpose: ["family", "companion"],
      healthStatus: "Very Good",
      vaccinationDetails: "Starter vaccine plan completed",
      rating: 4.6,
      reviewCount: 9,
      images: [
        "https://images.unsplash.com/photo-1543466835-00a7907e9de1?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1507146426996-ef05306b995a?auto=format&fit=crop&w=1200&q=80",
      ],
    },
    {
      id: 103,
      title: "Calm Boerboel Guard Prospect",
      category: "sale",
      breed: "Boerboel",
      gender: "male",
      state: "Ogun",
      city: "Abeokuta",
      price: 780000,
      ageMonths: 16,
      temperament: "moderate",
      isPedigree: true,
      isVaccinated: true,
      isFeatured: false,
      seller: "Prime Guard Dogs",
      sellerInitials: "PG",
      description: "Strong and balanced Boerboel with disciplined temperament, broad frame, and excellent guarding instincts.",
      purpose: ["security", "breeding"],
      healthStatus: "Excellent",
      vaccinationDetails: "Full schedule completed",
      rating: 4.7,
      reviewCount: 12,
      images: [
        "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1537151625747-768eb6cf92b2?auto=format&fit=crop&w=1200&q=80",
      ],
    },
    {
      id: 104,
      title: "Rescued Indie Pup Ready For Adoption",
      category: "adoption",
      breed: "Mixed Breed",
      gender: "female",
      state: "Enugu",
      city: "Independence Layout",
      price: 0,
      ageMonths: 8,
      temperament: "friendly",
      isPedigree: false,
      isVaccinated: true,
      isFeatured: true,
      seller: "Hope Tails Rescue",
      sellerInitials: "HT",
      description: "Healthy rescue puppy looking for a patient home. Loves short walks, responds well to affection, and has settled quickly into foster care.",
      purpose: ["adoption", "companion"],
      healthStatus: "Recovered and healthy",
      vaccinationDetails: "Rabies and deworming completed",
      rating: 4.9,
      reviewCount: 21,
      images: [
        "https://images.unsplash.com/photo-1561037404-61cd46aa615b?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?auto=format&fit=crop&w=1200&q=80",
      ],
    },
    {
      id: 105,
      title: "Healthy Beagle Pair For Mating",
      category: "mating",
      breed: "Beagle",
      gender: "male",
      state: "Rivers",
      city: "GRA",
      price: 150000,
      ageMonths: 24,
      temperament: "friendly",
      isPedigree: true,
      isVaccinated: true,
      isFeatured: false,
      seller: "Rivers K9 House",
      sellerInitials: "RK",
      description: "Stud Beagle with active temperament, great coat, and clean health records available for responsible mating arrangements.",
      purpose: ["mating", "breeding"],
      healthStatus: "Excellent",
      vaccinationDetails: "Annual boosters completed",
      rating: 4.5,
      reviewCount: 7,
      images: [
        "https://images.unsplash.com/photo-1534361960057-19889db9621e?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1505628346881-b72b27e84530?auto=format&fit=crop&w=1200&q=80",
      ],
    },
    {
      id: 106,
      title: "American Eskimo Family Companion",
      category: "sale",
      breed: "American Eskimo",
      gender: "female",
      state: "Oyo",
      city: "Ibadan",
      price: 360000,
      ageMonths: 10,
      temperament: "friendly",
      isPedigree: false,
      isVaccinated: true,
      isFeatured: false,
      seller: "City Paws Hub",
      sellerInitials: "CP",
      description: "Compact, energetic, and very affectionate dog suited for apartment families that still want a bold personality.",
      purpose: ["family", "companion"],
      healthStatus: "Very Good",
      vaccinationDetails: "All core vaccines updated",
      rating: 4.3,
      reviewCount: 5,
      images: [
        "https://images.unsplash.com/photo-1525253086316-d0c936c814f8?auto=format&fit=crop&w=1200&q=80",
      ],
    },
    {
      id: 107,
      title: "Gentle Rottweiler Rescue Adult",
      category: "adoption",
      breed: "Rottweiler",
      gender: "male",
      state: "Delta",
      city: "Asaba",
      price: 0,
      ageMonths: 30,
      temperament: "moderate",
      isPedigree: false,
      isVaccinated: true,
      isFeatured: false,
      seller: "Second Chance Dogs",
      sellerInitials: "SC",
      description: "An older rescue dog with calm energy and a steady personality. Best for adopters who want a settled adult companion.",
      purpose: ["adoption", "family"],
      healthStatus: "Good",
      vaccinationDetails: "Current on boosters",
      rating: 4.7,
      reviewCount: 11,
      images: [
        "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?auto=format&fit=crop&w=1200&q=80",
      ],
    },
    {
      id: 108,
      title: "Compact French Bulldog Stud",
      category: "mating",
      breed: "French Bulldog",
      gender: "male",
      state: "Lagos",
      city: "Yaba",
      price: 250000,
      ageMonths: 20,
      temperament: "friendly",
      isPedigree: true,
      isVaccinated: true,
      isFeatured: true,
      seller: "Urban K9 Loft",
      sellerInitials: "UK",
      description: "Short-nosed, compact stud option with breeding history, current health checks, and owner support through the process.",
      purpose: ["mating", "breeding"],
      healthStatus: "Excellent",
      vaccinationDetails: "Vet checked and current",
      rating: 4.8,
      reviewCount: 8,
      images: [
        "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=1200&q=80",
      ],
    },
  ],
  products: [
    {
      id: 201,
      name: "Premium Puppy Growth Meal",
      category: "food",
      brand: "Canis Gold",
      price: 32000,
      comparePrice: 38000,
      stock: 13,
      isFeatured: true,
      seller: "Pet Pantry NG",
      sellerInitials: "PP",
      rating: 4.8,
      reviewCount: 64,
      image: "https://images.unsplash.com/photo-1583511655857-d19b40a7a54e?auto=format&fit=crop&w=900&q=80",
      description: "Protein-rich dry food formulated for puppies under 12 months.",
    },
    {
      id: 202,
      name: "Joint Support Vitamins",
      category: "vitamins",
      brand: "PawLabs",
      price: 18500,
      comparePrice: 0,
      stock: 9,
      isFeatured: true,
      seller: "Vet Essentials",
      sellerInitials: "VE",
      rating: 4.6,
      reviewCount: 22,
      image: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=80",
      description: "Daily soft chews for mobility, bone strength, and recovery support.",
    },
    {
      id: 203,
      name: "Heavy Duty Leather Collar",
      category: "leash_collars",
      brand: "Trail Lead",
      price: 14500,
      comparePrice: 17500,
      stock: 18,
      isFeatured: false,
      seller: "Urban Tails Store",
      sellerInitials: "UT",
      rating: 4.4,
      reviewCount: 18,
      image: "https://images.unsplash.com/photo-1518715308788-de9717d6b2b4?auto=format&fit=crop&w=900&q=80",
      description: "Wide padded collar for medium to large breeds with reinforced buckle.",
    },
    {
      id: 204,
      name: "Flea And Tick Shield Spray",
      category: "tick_flea",
      brand: "GuardPet",
      price: 9600,
      comparePrice: 12000,
      stock: 24,
      isFeatured: false,
      seller: "Pet Pantry NG",
      sellerInitials: "PP",
      rating: 4.3,
      reviewCount: 12,
      image: "https://images.unsplash.com/photo-1517842645767-c639042777db?auto=format&fit=crop&w=900&q=80",
      description: "Topical protection spray for weekly grooming and parasite prevention.",
    },
    {
      id: 205,
      name: "Shedding Control Grooming Kit",
      category: "grooming",
      brand: "Clean Coat",
      price: 22500,
      comparePrice: 0,
      stock: 7,
      isFeatured: true,
      seller: "Groom Lab",
      sellerInitials: "GL",
      rating: 4.9,
      reviewCount: 41,
      image: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?auto=format&fit=crop&w=900&q=80",
      description: "Brush, comb, shampoo, and nail clipper set for weekly home grooming.",
    },
    {
      id: 206,
      name: "Slow Feed Bowl Set",
      category: "bowls_feeders",
      brand: "Calm Chow",
      price: 11000,
      comparePrice: 0,
      stock: 30,
      isFeatured: false,
      seller: "Urban Tails Store",
      sellerInitials: "UT",
      rating: 4.2,
      reviewCount: 15,
      image: "https://images.unsplash.com/photo-1518717758536-85ae29035b6d?auto=format&fit=crop&w=900&q=80",
      description: "Twin bowl design that slows eating and reduces messy feeding.",
    },
    {
      id: 207,
      name: "Orthopedic Dog Bed",
      category: "beds_cages",
      brand: "RestWell",
      price: 54000,
      comparePrice: 62000,
      stock: 4,
      isFeatured: true,
      seller: "Rest Kennels",
      sellerInitials: "RK",
      rating: 4.8,
      reviewCount: 26,
      image: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?auto=format&fit=crop&w=900&q=80",
      description: "Supportive memory-foam bed built for large breeds and senior dogs.",
    },
    {
      id: 208,
      name: "Travel Medical Record Folder",
      category: "medical_cards",
      brand: "VetFile",
      price: 7800,
      comparePrice: 0,
      stock: 25,
      isFeatured: false,
      seller: "Vet Essentials",
      sellerInitials: "VE",
      rating: 4.1,
      reviewCount: 8,
      image: "https://images.unsplash.com/photo-1583512603806-077998240c7a?auto=format&fit=crop&w=900&q=80",
      description: "Document wallet for vaccination cards, receipts, and treatment records.",
    },
  ],
  serviceHighlights: [
    {
      title: "Home Visits",
      description: "Book veterinary visits for dogs that should not travel or owners who prefer care at home.",
    },
    {
      title: "Vaccination Plans",
      description: "Get age-appropriate vaccination guidance and reminders from qualified professionals.",
    },
    {
      title: "Diagnostics",
      description: "Request support for parasite checks, blood work, and follow-up treatment planning.",
    },
    {
      title: "Emergency Triage",
      description: "Start urgent intake quickly so the admin team can route your case to the right provider.",
    },
  ],
  faq: [
    {
      question: "How do payments work?",
      answer: "The frontend keeps the original safety policy: buyers should pay through NaijaPaws-admin-managed channels, not directly to sellers.",
    },
    {
      question: "Can I still use the backend later?",
      answer: "Yes. This frontend is now standalone HTML, CSS, and JavaScript, so API wiring can be added later without changing the page structure again.",
    },
    {
      question: "Are seller applications live?",
      answer: "In this frontend conversion they are stored locally in the browser to preserve the interaction flow until a backend endpoint is connected.",
    },
  ],
};
